# Generated by Django 3.2.3 on 2021-05-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210523_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(blank=True, height_field='238', null=True, upload_to='', verbose_name='Image', width_field='238'),
        ),
    ]
